version: '3'
services:
  javacontainer:
    build: javaprogram

  pythoncontainer:
    build: pythonprogram
    depends_on:
      - javacontainer

  rustcontainer:
    build: rustprogram
    depends_on:
      - pythoncontainer
